### ISSUE TITLE
map.dat files loading problem under Windows

### ISSUE THREAD

**Issue by walraymmo** [dogbreaf/Mishkas-Engine#4]
I tried to start the game on Windows and I got this result.

![image](https://user-images.githubusercontent.com/48967105/75460110-5500f200-5981-11ea-932d-a068d03e5478.png)

Discover that it only happens with the files that the project carries (files generated on linux i suppose), if I generate a new one it doesn't happen, using Linux the problem is not present.

tried converting the backspaces of the file to Windows format, but it didn't work.

**Comment by dogbreaf** [comment]
The issue seems to be related to the 32bit version of FreeBASIC (I had only tested with 64bit on windows and linux), some data type probably has a different size and so its reading the data incorrectly. I'll look into it and see what I can do. In the meantime files created on 32bit and 64bit versions won't be compatable.

**Comment by walraymmo** [comment]
Understood, for the moment i will try compile with 64, thanks for your response.

**Comment by dogbreaf** [comment]
This is fixed in experemental now.
